### ISSUE TITLE
Tariq Model

### ISSUE THREAD

**Issue by hallegu** [Boogey007/Attend-In#16]

**Comment by tariq121** [comment]
[https://app.zenhub.com/files/335410053/0a438cae-ff7b-4579-b327-8133cbc979d1/download](https://app.zenhub.com/files/335410053/0a438cae-ff7b-4579-b327-8133cbc979d1/download)

**Comment by tariq121** [comment]
[https://app.zenhub.com/files/335410053/ac20a87e-6c51-4822-b46d-b2d7916b8089/download](https://app.zenhub.com/files/335410053/ac20a87e-6c51-4822-b46d-b2d7916b8089/download)
