### ISSUE TITLE
Samson Model

### ISSUE THREAD

**Issue by hallegu** [Boogey007/Attend-In#17]

**Comment by Samson-Gebreegziabher** [comment]
[conceptual model.jpg](https://images.zenhubusercontent.com/6019b2f38c31d37808d4b557/07f970c8-95fe-4036-b98c-71ee463d4493)

**Comment by Samson-Gebreegziabher** [comment]
[https://app.zenhub.com/files/335410053/9062714e-9f6c-431d-b6c1-29796bf00566/download](https://app.zenhub.com/files/335410053/9062714e-9f6c-431d-b6c1-29796bf00566/download)
