### ISSUE TITLE
Learn About GeoFencing

### ISSUE THREAD

**Issue by joseishere** [Boogey007/Attend-In#2]

**Comment by hallegu** [comment]
Looked at some of the sample code and read about functionality/browser support on this tutorial (linked in Discord by Jose): https://www.w3schools.com/html/html5_geolocation.asp

I'm pleasantly surprised at the accuracy I got by trying it on my device (within 0.000000000001 of a degree of longitude/latitude?). If this is at all indicative of what we can expect from our app, we should definitely have enough accuracy to facilitate classroom location checks.
