### ISSUE TITLE
Jacob wireframe

### ISSUE THREAD

**Issue by hallegu** [Boogey007/Attend-In#24]

**Comment by jkobb510** [comment]
![Screen Shot 2021-02-07 at 11.16.59 AM.png](https://images.zenhubusercontent.com/601c1dc65322cf02b99d4db5/322dc174-4c95-4152-aef8-b55fe0c2d65d)![Screen Shot 2021-02-07 at 11.14.05 AM.png](https://images.zenhubusercontent.com/601c1dc65322cf02b99d4db5/13c48e12-0ada-4a30-b797-a4eee1f020c8)![Screen Shot 2021-02-07 at 11.14.09 AM.png](https://images.zenhubusercontent.com/601c1dc65322cf02b99d4db5/929a8ee6-cf9f-4177-b2c3-962be031fa33)
