### ISSUE TITLE
Finalize unified Wireframe model

### ISSUE THREAD

**Issue by hallegu** [Boogey007/Attend-In#26]

**Comment by Boogey007** [comment]
[CamScanner 02-15-2021 12.35.pdf](https://github.com/Boogey007/Attend-In/files/5983235/CamScanner.02-15-2021.12.35.pdf)

**Comment by joseishere** [comment]
[https://app.zenhub.com/files/335410053/6f6f1630-7a3a-4b7f-8333-bedb5db3f0be/download](https://app.zenhub.com/files/335410053/6f6f1630-7a3a-4b7f-8333-bedb5db3f0be/download)![overview.PNG](https://images.zenhubusercontent.com/6019b248ba808f3bfb954fa2/162c0c77-459f-4445-8b07-cd19778e671d)

**Comment by joseishere** [comment]
Link to the figma, the page that I used to make the wireframes digital

https://www.figma.com/file/FCDiUoFtJd3c5VxSva86hC/AttendIn_wireframes_done?node-id=0%3A1

And the link to the color palette I used so we can have it for future reference

https://coolors.co/0081af-2c5530-db3a34-cbd2d0-323031
