### ISSUE TITLE
UML Sequence Diagrams

### ISSUE THREAD

**Issue by hallegu** [Boogey007/Attend-In#39]
At least 3, hand-drawn diagrams, "each a distinct and different process in the application". Each diagram should also have at least 4 interacting objects

**Comment by joseishere** [comment]
[https://app.zenhub.com/files/335410053/7e955e29-4063-40dd-befb-8c4c8d4734e9/download](https://app.zenhub.com/files/335410053/7e955e29-4063-40dd-befb-8c4c8d4734e9/download)

**Comment by joseishere** [comment]
Dropping my sequence diagram here

![IMG_1276.JPG](https://images.zenhubusercontent.com/6019b248ba808f3bfb954fa2/48e6ae3c-e7be-473a-be42-1beea78f88d0)
