### ISSUE TITLE
UML Sequence Diagrams #1

### ISSUE THREAD

**Issue by Boogey007** [Boogey007/Attend-In#42]

**Comment by hallegu** [comment]
A sequence diagram I drew to illustrate the process of checking in attendance from the Student's perspective![UML_Process_student_checkin.png](https://images.zenhubusercontent.com/60132ce9a91eae7537b40f8d/c4cd62d6-b53f-4a07-90eb-7ced2c73238d)

**Comment by hallegu** [comment]
![sequence diagram_student_checkin.png](https://images.zenhubusercontent.com/60132ce9a91eae7537b40f8d/c3dbbc9a-e7ce-4d9d-8192-09e738d14209)
Sequence diagram to illustrate interactions involved in User checking in attendance in the app. Involves User, App interface, Database, and GPS.
