### ISSUE TITLE
UML Case Diagrams #1

### ISSUE THREAD

**Issue by Boogey007** [Boogey007/Attend-In#49]

**Comment by hallegu** [comment]
Edited original Use-Case per Johnson's suggestions
![use_case_newaccount.png](https://images.zenhubusercontent.com/60132ce9a91eae7537b40f8d/8a94ff98-25e2-4dcd-a507-f913cce57df3)

Another one
![use_case_newaccount.png](https://images.zenhubusercontent.com/60132ce9a91eae7537b40f8d/93309190-310f-4287-b05a-6e498a7ec8b2)
